version: "3.9"
services:
  cassandra:
    image: cassandra:4.0.1
    ports:
      - '9042:9042'
    volumes:
      - ./data/cassandra:/var/lib/cassandra
  csqlsh:
      image: cassandra:4.0.1
      entrypoint: cqlsh cassandra